[backup]
command:/usr/local/opnsense/scripts/Automatisierung/backup_job.py
parameters:
type:script_output
message:running Automatisierung backup job
description:Automatisierung: Run configuration backup

[watchdog]
command:/usr/local/opnsense/scripts/Automatisierung/za_watchdog.py
parameters:
type:script_output
message:running ZA watchdog check
description:Automatisierung: Run Zenarmor watchdog check
